name: build-ssg
run-name: Build static site generator

on:
  workflow_dispatch:
  push:
    tags: [v*]
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET: "x86_64-unknown-linux-gnu"
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
        with:
          add-rust-environment-hash-key: false
      - name: Build
        run: cargo build --release --target "$TARGET"
      - run: mv "target/$TARGET/release/blog" "blog-$TARGET"
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create '${{ github.ref_name }}' --notes-from-tag "blog-$TARGET"

  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: $/.github/workflows/deploy.yml
