name: build-ssg
run-name: Build static site generator

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET: "x86_64-unknown-linux-gnu"
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target "$TARGET"
      - run: mv "target/$TARGET/release/blog" "blog-$TARGET"
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          path: blog-${{ env.TARGET }}
          name: blog-${{ env.TARGET }}

  upload:
    runs-on: ubuntu-latest
    needs: build
    env:
      TARGET: "x86_64-unknown-linux-gnu"
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v7
        id: download
        with:
          name: blog-${{ env.TARGET }}
      - name: Upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload '${{ github.ref_name }}' "${{ steps.download.outputs.download-path }}/blog-$TARGET"

  deploy:
    needs: upload
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: $/.github/workflows/deploy.yml
